In [12]:
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import talib
# TASI index or company ticker (e.g., Al Rajhi Bank: 1120.SR)
# ticker = "2222.SR"
# df = yf.download(ticker, start="2020-01-01", interval="1d")
# print(df.tail())

In [21]:
yf_tickers = [
    "2140.SR",  # ADC / Ayyan
    "1120.SR",  # ALRAJHI
    "4220.SR",  # EMAAR EC
    "4180.SR",  # FITAIHI GROUP
    "6020.SR",  # GACO
    "2280.SR",  # SARCO
    "5110.SR",  # SAUDI ELECTRICITY
    "2070.SR",  # SPIMACO
    "7010.SR",  # STC
    "2060.SR",  # TASNEE
]

In [ ]:
# df = pd.DataFrame(yf.download('2222.SR', start="2020-01-01", interval='1d'))
# filename = '2222.SR'+'.csv'
# df.to_csv(filename,index=False)

[*********************100%***********************]  1 of 1 completed

In [27]:
for tick in yf_tickers:
    df = pd.DataFrame(yf.download(tick, start="2020-01-01", interval='1d'))
    filename = tick+'.csv'
    df.to_csv(filename,index=False)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [6]:
df = pd.DataFrame(yf.download('2222.SR', period='max', interval='1d',actions=True))

[*********************100%***********************]  1 of 1 completed

In [7]:
df

Price,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,2222.SR,2222.SR,2222.SR,2222.SR,2222.SR,2222.SR,2222.SR
Date,,,,,,,
2019-12-11,21.520964,0.0,21.520964,21.520964,21.520964,0.0,38289394
2019-12-12,22.499189,0.0,23.660832,22.010076,23.660832,0.0,505692621
2019-12-15,22.866030,0.0,22.927169,22.499196,22.682613,0.0,98349281
2019-12-16,23.232861,0.0,23.293999,22.927165,22.927165,0.0,105973907
2019-12-17,23.080011,0.0,23.324567,22.927164,23.263428,0.0,142672245
...,...,...,...,...,...,...,...
2026-10-04,25.420000,0.0,25.500000,25.299999,25.400000,0.0,3475900
2026-10-05,25.559999,0.0,25.719999,25.299999,25.299999,0.0,12499467
2026-10-06,25.799999,0.0,26.000000,25.680000,25.780001,0.0,13764976
2026-10-07,25.840000,0.0,25.840000,25.660000,25.799999,0.0,6076351
2026-10-08,25.740000,0.0,26.040001,25.719999,25.840000,0.0,16824618

In [13]:
df = yf.Ticker("2222.SR").history(period="6mo")

In [14]:
df['SMA_20'] = talib.SMA(df['Close'], timeperiod=20)

In [15]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_20
Date,,,,,,,,
2026-04-08 00:00:00+03:00,26.364546,26.462047,25.955038,26.306044,25739181,0.0,0.0,NaN
2026-04-09 00:00:00+03:00,26.286540,26.520546,26.228039,26.520546,15586501,0.0,0.0,NaN
2026-04-12 00:00:00+03:00,26.442547,26.559548,26.442547,26.481546,5159433,0.0,0.0,NaN
2026-04-13 00:00:00+03:00,26.579048,26.910555,26.540046,26.910555,23590561,0.0,0.0,NaN
2026-04-14 00:00:00+03:00,26.871553,26.871553,26.540046,26.676550,15109225,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...
2026-10-04 00:00:00+03:00,25.400000,25.500000,25.299999,25.420000,3475900,0.0,0.0,25.688
2026-10-05 00:00:00+03:00,25.299999,25.719999,25.299999,25.559999,12499467,0.0,0.0,25.668
2026-10-06 00:00:00+03:00,25.780001,26.000000,25.680000,25.799999,13764976,0.0,0.0,25.660
2026-10-07 00:00:00+03:00,25.799999,25.840000,25.660000,25.840000,6076351,0.0,0.0,25.649
2026-10-08 00:00:00+03:00,25.840000,26.040001,25.719999,25.740000,16824618,0.0,0.0,25.634

In [16]:
df['RSI_14'] = talib.RSI(df['Close'], timeperiod=14)

In [17]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_20,RSI_14
Date,,,,,,,,,
2026-04-08 00:00:00+03:00,26.364546,26.462047,25.955038,26.306044,25739181,0.0,0.0,NaN,NaN
2026-04-09 00:00:00+03:00,26.286540,26.520546,26.228039,26.520546,15586501,0.0,0.0,NaN,NaN
2026-04-12 00:00:00+03:00,26.442547,26.559548,26.442547,26.481546,5159433,0.0,0.0,NaN,NaN
2026-04-13 00:00:00+03:00,26.579048,26.910555,26.540046,26.910555,23590561,0.0,0.0,NaN,NaN
2026-04-14 00:00:00+03:00,26.871553,26.871553,26.540046,26.676550,15109225,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2026-10-04 00:00:00+03:00,25.400000,25.500000,25.299999,25.420000,3475900,0.0,0.0,25.688,41.228310
2026-10-05 00:00:00+03:00,25.299999,25.719999,25.299999,25.559999,12499467,0.0,0.0,25.668,45.455562
2026-10-06 00:00:00+03:00,25.780001,26.000000,25.680000,25.799999,13764976,0.0,0.0,25.660,51.849392
2026-10-07 00:00:00+03:00,25.799999,25.840000,25.660000,25.840000,6076351,0.0,0.0,25.649,52.841624
2026-10-08 00:00:00+03:00,25.840000,26.040001,25.719999,25.740000,16824618,0.0,0.0,25.634,50.064121

In [18]:
df['MACD'], df['MACD_Signal'], df['MACD_Hist'] = talib.MACD(df['Close'], fastperiod=12, slowperiod=26, signalperiod=9)

In [19]:
print(df[['Close', 'SMA_20', 'RSI_14', 'MACD']].tail())

                               Close  SMA_20     RSI_14      MACD
Date
2026-10-04 00:00:00+03:00  25.420000  25.688  41.228310 -0.198959
2026-10-05 00:00:00+03:00  25.559999  25.668  45.455562 -0.181601
2026-10-06 00:00:00+03:00  25.799999  25.660  51.849392 -0.146786
2026-10-07 00:00:00+03:00  25.840000  25.649  52.841624 -0.114646
2026-10-08 00:00:00+03:00  25.740000  25.634  50.064121 -0.096136

In [20]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_20,RSI_14,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,
2026-04-08 00:00:00+03:00,26.364546,26.462047,25.955038,26.306044,25739181,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2026-04-09 00:00:00+03:00,26.286540,26.520546,26.228039,26.520546,15586501,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2026-04-12 00:00:00+03:00,26.442547,26.559548,26.442547,26.481546,5159433,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2026-04-13 00:00:00+03:00,26.579048,26.910555,26.540046,26.910555,23590561,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2026-04-14 00:00:00+03:00,26.871553,26.871553,26.540046,26.676550,15109225,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-10-04 00:00:00+03:00,25.400000,25.500000,25.299999,25.420000,3475900,0.0,0.0,25.688,41.228310,-0.198959,-0.167758,-0.031201
2026-10-05 00:00:00+03:00,25.299999,25.719999,25.299999,25.559999,12499467,0.0,0.0,25.668,45.455562,-0.181601,-0.170526,-0.011075
2026-10-06 00:00:00+03:00,25.780001,26.000000,25.680000,25.799999,13764976,0.0,0.0,25.660,51.849392,-0.146786,-0.165778,0.018992
2026-10-07 00:00:00+03:00,25.799999,25.840000,25.660000,25.840000,6076351,0.0,0.0,25.649,52.841624,-0.114646,-0.155552,0.040906
2026-10-08 00:00:00+03:00,25.840000,26.040001,25.719999,25.740000,16824618,0.0,0.0,25.634,50.064121,-0.096136,-0.143669,0.047533